### ISSUE TITLE
Article: universal domain types

### ISSUE THREAD

**Issue by roman-kashitsyn** [roman-kashitsyn/mmapped.blog#50]

**Comment by wildthink** [comment]
Very, very interesting. 
In particular, w/ regard to Loci: it seems that a `Region` type might be distinctive enough to warrant its own type. A more general form of a numeric Range, if you will.

I also frequently reflect on the best/proper way to handle "versions of entities". There is decidedly some distinct comparative operations that would apply.

Again, insightful. Thanks.

**Comment by peter-lyons-kehl** [comment]
Jason @wildthink What would be "versions of entities?" Versions/history and/or deltas of an object's values?
