### ISSUE TITLE
Add a link to `phantom-newtype` repo in the `Universal domain types` article

### ISSUE THREAD

**Issue by berestovskyy** [roman-kashitsyn/mmapped.blog#63]
1. https://github.com/roman-kashitsyn/phantom-newtype
2. https://mmapped.blog/posts/25-domain-types

**Comment by roman-kashitsyn** [comment]
The post has a link to the crates.io package in [conclusion](https://mmapped.blog/posts/25-domain-types.html#conclusion):

> I’m sure you will identify a few places in your application where one of these type classes fits perfectly. If you use Rust, you might find my [phantom_newtype](https://crates.io/crates/phantom_newtype) package helpful. Maybe you’ll discover some gems of your own. Have fun!

**Comment by berestovskyy** [comment]
Sorry, I missed it.
