### ISSUE TITLE
Footnotes don't appear on mobile

### ISSUE THREAD

**Issue by asuraphel** [roman-kashitsyn/mmapped.blog#70]
Your blog is beautiful. 

However I noticed that footnotes disappear when you switch to mobile.

**Comment by roman-kashitsyn** [comment]
> However I noticed that footnotes disappear when you switch to mobile.

The sidenotes are still available on mobile, but they are less discoverable. You need to tap on the sidenote mark (the superscript number), and the sidenote section will expand in place.

**Comment by roman-kashitsyn** [comment]
I made sidenote numerals underlined on narrow screens to indicate that you can click on them.

**Comment by asuraphel** [comment]
> I made sidenote numerals underlined on narrow screens to indicate that you can click on them.

Awesome!
